random_seed: 42
data_path: data/cup_race_results_2014_2024.csv
champions_path: data/champions_2014_2024.csv

generate_grouped_data: False

target_variable: wins
predictors:
  force_categorical:
    - race_season
  include: []  # Empty: uses automatic predictor selection
  exclude: # if empty: no manual exclusions (automatic exclusions still apply)
    - avg_diff_time_sec
    - avg_diff_time_min
    - total_laps
    - avg_starting_position
    - top_5
    - top_10
    - total_laps_led  
    - num_races

train_test_split:
  test_size: 0.3
  stratify: race_season  # Stratifies by race_season - ensures relatively similar distribution among train & test

cross_validation:
  folds: 5  # Enables 5-fold CV; set to null or omit to disable

models:
  ols: false
  poisson: false
  neg_binomial: false
  zero_inflated_poisson: false
  zero_inflated_neg_binomial: false
  xgboost: true  # Explicitly enable xgboost
  gbm: false      # Explicitly enable gbm

hyperparameters:
  xgboost:
    enabled: true
    search_type: randomized  # Switch to RandomizedSearchCV
    n_iter: 50              # Number of random combinations to try 50 x 5 = 250 fits
    param_grid:
      max_depth: [3, 5, 7]
      learning_rate: [0.01, 0.1, 0.3]
      n_estimators: [50, 100, 200]
      min_child_weight: [1, 3]
      subsample: [0.8, 1.0]
      colsample_bytree: [0.8, 1.0]
    early_stopping_rounds: 10  # Enable early stopping
    cv_folds: 5
    n_jobs: 2  # Limit to 2 cores to avoid overload
  gbm:
    enabled: true
    search_type: randomized
    n_iter: 50
    param_grid:
      max_depth: [3, 5, 7]
      learning_rate: [0.01, 0.1, 0.3]
      n_estimators: [50, 100, 200]
      min_samples_split: [2, 5]
      min_samples_leaf: [1, 2]
    early_stopping_rounds: 10
    cv_folds: 5
    n_jobs: 2

model_selection:
  # manual_model_id: gbm_20250311_2138  # e.g., ols_20240315_143500 if manually selecting else null
  manual_model_id: poisson_20250312_1409
  # manual_model_id: null
  metric: test_RMSE
  minimize: true

output:
  save_models: true
  leaderboard_csv: leaderboard.csv
  OU_sort_column: win_diff
  driver_sort_ascending: False

visualization:
  default_display: true   # Master switch - if False, PDPs are skipped
  pdp_features: null        # if empty, defaults to PDPs for top 10 features